### ISSUE TITLE
php error при добавлении новых данных в график при нажатии кнопки сохранить

### ISSUE THREAD

**Issue by xor2016** [sergejey/majordomo-charts#21]
https://github.com/sergejey/majordomo-charts/blob/5624da2d5fbd06dbe6119d7e90f59dc62bfab42f/modules/charts/charts.class.php#L318

при еще незаполненных данных по данным в лог апача пишется ошибка при сохранении нового ряда данных:
`PHP Fatal error:  Uncaught Error: Call to a member function getPropertyByName() on int in C:\\_majordomo\\htdocs\\modules\\charts\\charts.class.php:319\nStack trace:\n#0 C:\\_majordomo\\htdocs\\modules\\charts\\charts.class.php(105): charts->usual(Array)\n#1 C:\\_majordomo\\htdocs\\modules\\application.class.php(399) : eval()'d code(5): charts->run()\n#2 C:\\_majordomo\\htdocs\\modules\\application.class.php(399): eval()\n#3 C:\\_majordomo\\htdocs\\index.php(42): application->run()\n#4 C:\\_majordomo\\htdocs\\nf.php(151): include_once('C:\\\\_majordomo\\\\h...')\n#5 {main}\n  thrown in C:\\_majordomo\\htdocs\\modules\\charts\\charts.class.php on line 319,`

обходится добавлением следующей строки перед 319
`318 $obj = getObject($chart_data['LINKED_OBJECT']);`
 `... if(!$obj) exit;`
`319 $prop_id = $obj->getPropertyByName($chart_data['LINKED_PROPERTY'], $obj->class_id, $obj->id);`

**Comment by sergejey** [comment]
Исправил в обновлении.
